### PR TITLE
Trying new dockerfile

### PR DESCRIPTION
**Pull request by muschellij2**
The build I pushed failed: https://hub.docker.com/r/seankross/bologna/builds/ I think the new build should run but it takes like 91 minutes.

Maybe we can check to see if this built on travis?

### CODE REVIEW

**Comment by seankross** [comment]
@muschellij2 Are you sure you need to install imagemagick? I think it's already installed here: https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile#L23

**Comment by muschellij2** [comment]
So `libmagick++-dev` are the C++ bindings for ImageMagick, which the `magick` package uses.  I should have used that package but already had code using ImageMagick, the binary software, which the `animation` package uses.  `didactr` uses `animation`, which uses function `convert` from ImageMagick.  So `imagemagick` still needs to be installed on top of the C++ bindings.  If we move to `magick`, then this can be avoided.

**Comment by seankross** [comment]
Ahhhhh I see. @jtleek was having some issues with imagemagick FYI.

**Comment by muschellij2** [comment]
Should be resolved when this dockerfile gets built on dockerhub.

John

**Pull request merged**
